trash.conf, util/process.go, util/util_test.go, vendor/github.com/c9s/goprocinfo/.gitignore, vendor/github.com/c9s/goprocinfo/LICENSE, vendor/github.com/c9s/goprocinfo/README.md, vendor/github.com/c9s/goprocinfo/linux/cpuinfo.go, vendor/github.com/c9s/goprocinfo/linux/disk.go, vendor/github.com/c9s/goprocinfo/linux/diskstat.go, vendor/github.com/c9s/goprocinfo/linux/interrupts.go, vendor/github.com/c9s/goprocinfo/linux/loadavg.go, vendor/github.com/c9s/goprocinfo/linux/meminfo.go, vendor/github.com/c9s/goprocinfo/linux/mounts.go, vendor/github.com/c9s/goprocinfo/linux/net_ip.go, vendor/github.com/c9s/goprocinfo/linux/net_tcp.go, vendor/github.com/c9s/goprocinfo/linux/net_udp.go, vendor/github.com/c9s/goprocinfo/linux/netstat.go, vendor/github.com/c9s/goprocinfo/linux/network_stat.go, vendor/github.com/c9s/goprocinfo/linux/process.go, vendor/github.com/c9s/goprocinfo/linux/process_cmdline.go, vendor/github.com/c9s/goprocinfo/linux/process_io.go, vendor/github.com/c9s/goprocinfo/linux/process_pid.go, vendor/github.com/c9s/goprocinfo/linux/process_stat.go, vendor/github.com/c9s/goprocinfo/linux/process_statm.go, vendor/github.com/c9s/goprocinfo/linux/process_status.go, vendor/github.com/c9s/goprocinfo/linux/snmp.go, vendor/github.com/c9s/goprocinfo/linux/sockstat.go, vendor/github.com/c9s/goprocinfo/linux/stat.go, vendor/github.com/c9s/goprocinfo/linux/uptime.go, vendor/github.com/c9s/goprocinfo/linux/vmstat.go
Then longhorn-manager and longhorn-engine will search `dockerd` by `ProcessFinder`.
The rough code will be:
```
procPath := getProcPath()
pf := new ProcessFinder(procPath)
ps, _  := pf.FindTarget("dockerd")
if ps == nil {
logrus.Infof("Failed to search dockerd, pid1 will be used")
return 1
}
return ps.Pid
```
=> Add ProcessFinder

util/process.go
https://github.com/rancher/longhorn/issues/501
=> added func FindHostNamespacePID()

Dockerfile.dapper
Signed-off-by: Sheng Yang <sheng.yang@rancher.com>
=> Upgrade golang to v1.13.3

longhorndev/dev.go
https://github.com/longhorn/longhorn/issues/879
=> Skip operating socket file for DR volume

iscsi/initiator.go, iscsi/target.go, iscsiblk/iscsi.go, longhorndev/dev.go
=> Modification for volume expansion

iscsi/target.go
Signed-off-by: Sheng Yang <sheng.yang@rancher.com>
=> iscsi: Check for existing running tgtd

iscsi/initiator.go, iscsi/iscsi_test.go, iscsidev/iscsi.go
Longhorn #1027
Signed-off-by: Sheng Yang <sheng.yang@rancher.com>
=> Update iscsi target name prefix to `iqn.2019-10.io.longhorn:`

iscsi/target.go
Signed-off-by: Sheng Yang <sheng.yang@rancher.com>
=> iscsi: Use target state to indicate if tgtd is running

longhorndev/dev.go
=> Set endpoint during the upgrade

.gitignore
Signed-off-by: Joshua Moody <joshua.moody@rancher.com>
=> Update .gitignore for goland and dapper

longhorndev/dev.go
The ISCSI init function is used to set parameters and try to clean up possible leftovers before the ISCSI start.
longhorn/longhorn#1240
=> Decouple ISCSI device init from ISCSI device start

longhorndev/dev.go
longhorn/longhorn#1408
Signed-off-by: Joshua Moody <joshua.moody@rancher.com>
=> Fix ticker leakage

iscsi/initiator.go
Since Rancher Labs always wants to be open and prevent vendor lock-in :) , we implement this fix to support users who use Longhorn along with other CSI Drivers which require that the `node.session.scan` on nodes has to be `manual`.
Added a function to detect when `node.session.scan=manual` and perform a manual rescan LUNs of the new tgt target only. Otherwise,` iscsi login process` automatically rescans all iscsi sessions by default.
longhorn/longhorn#1612
=> iscsi: add function to detect node.session.scan mode. If node.session scan mode = manualy , manually rescan the new tgt target only

iscsi/initiator.go, iscsidev/iscsi.go
=> Log out all session for a target

util/util.go
=> Wrap underlying os.exec error so we can process the programs exit code

longhorndev/dev.go
https://github.com/longhorn/longhorn/issues/4362
=> troubleshoot: improve init frontend error

iscsi/initiator.go, iscsi/iscsi_test.go, iscsi/target.go, iscsidev/iscsi.go, longhorndev/dev.go, util/util.go
https://github.com/longhorn/longhorn/issues/4599
Signed-off-by: Derek Su [derek.su@suse.com](mailto:derek.su@suse.com)
=> Customize iSCSI LUN's block size

iscsi/iscsi_test.go, iscsi/target.go, iscsidev/iscsi.go, longhorndev/dev.go
Update filesystem block size instead of the Lun block size.
[Longhorn 4599](https://github.com/longhorn/longhorn/issues/4599)
=> Revert for Customize iSCSI LUN's block size

iscsi/initiator.go, iscsi/target.go, iscsidev/iscsi.go, longhorndev/dev.go, util/process.go, util/util.go
[Longhorn 4491](https://github.com/longhorn/longhorn/issues/4491)
=> Support customized scsi dev timeout and iSCSI initiator/target timeouts

iscsi/initiator.go, iscsi/target.go, iscsidev/iscsi.go, longhorndev/dev.go, types/tgtadm_errors.go
[Longhorn 4959
](https://github.com/longhorn/longhorn/issues/4959)
=> Add error handling for iSCSI operations

Dockerfile.dapper, iscsi/initiator.go, iscsi/target.go, iscsidev/iscsi.go, longhorndev/dev.go
Some of the changes are actually from [the deprecated PR](https://github.com/longhorn/go-iscsi-helper/pull/17)
longhorn/longhorn#1674
=> Online expansion support

.github/dependabot.yml
Signed-off-by: David Ko <dko@suse.com>
=> ci: add dependency bot

iscsi/target.go, iscsidev/iscsi.go
=> Set write-cache to off explicitly

iscsi/initiator.go, iscsi/target.go, iscsidev/iscsi.go, longhorndev/dev.go, types/tgtadm_errors.go
https://github.com/longhorn/longhorn/issues/4965
https://github.com/longhorn/longhorn/issues/4959
=> [BACKPORT][v1.3.3] Add error handling for iSCSI operations

iscsi/target.go, iscsidev/iscsi.go
=> [BACKPORT][v1.3.x] Set write-cache to off explicitly

longhorndev/dev.go
=> Fix error caused by incorrect select case statement

iscsi/initiator.go
Issue longhorn/longhorn#2259
Support for IPv6.
`None`
`None`
=> feat(ipv6): support address family
